### ISSUE TITLE
Reset the values to null for “Show Total Cash Held” and “Press to Collect Cash” when the Maintainer successfully pushes “Press Here When Finished”

### ISSUE THREAD

**Issue by ssraghavendra** [nkevins/vmcs#1]
The simulation currently does not clear the values on the completion of a Maintenance session. Upon a subsequent re-login to the Maintenance Panel in the same session, the cash previously held and already collected, persists in the display. This sometimes causes confusion to Maintainer.

**Comment by nkevins** [comment]
@voonlongs , please assist to resolve this bug.
Thanks.

**Comment by voonlongs** [comment]
bug had been fixed and the pull request #5 had been submitted to merge

**Comment by kyawminthu** [comment]
Tested the bug fix. Close the issue.

**Comment by madman777** [comment]
The bug has been fixed successfully.

**Comment by nkevins** [comment]
Released on RC1.0.9
