### ISSUE TITLE
Display the cash amount held per denomination

### ISSUE THREAD

**Issue by ssraghavendra** [nkevins/vmcs#2]
Upon successfully logging in to the drinks dispenser machine,
a. The Maintainer will be able to press “Show Total Cash Held’. In so doing, a display of not only the Total Cash Held is displayed, the specific Quantity of coins per denomination together with its total cash Amount/value per denomination are calculated and displayed.
b. The Maintainer should be able to more readily compare the individual Amount by denomination with the Total Cash Held.
c. Next, the Maintainer should push the “Press To Collect All Cash”. The number of coins dispensed should tally with the total number of coins in inventory for each denomination.
d. Finally, the Maintainer will simulate to indicate “Door Locked” in the Machinery Panel, as per normal, and will “Press Here When Finished” his routine maintenance on the vending machine.

**Comment by nkevins** [comment]
DMR has been updated.
@zawminthantt please assist with this enhancement.

**Comment by madman777** [comment]
The change has been tested successfully.

**Comment by nkevins** [comment]
Released on RC1.0.9
